array (
  0 => 
  array (
    'name' => 'Павел Солнцев',
    'username' => 'pavelsolnsev',
    'goals' => 69,
    'gamesPlayed' => 205,
    'wins' => 79,
    'draws' => 61,
    'losses' => 65,
    'rating' => 112.1,
    'photo' => 'pavelsolnsev.png',
  ),
  1 => 
  array (
    'name' => 'Ислам Халиков',
    'username' => '@unknown',
    'goals' => 82,
    'gamesPlayed' => 198,
    'wins' => 76,
    'draws' => 57,
    'losses' => 65,
    'rating' => 104.1,
    'photo' => 'islam.png',
  ),
  2 => 
  array (
    'name' => 'Даниил Турланов',
    'username' => '@unknown',
    'goals' => 33,
    'gamesPlayed' => 106,
    'wins' => 49,
    'draws' => 30,
    'losses' => 27,
    'rating' => 100.7,
    'photo' => 'tyrlanov.png',
  ),
  3 => 
  array (
    'name' => 'Иван Семенников',
    'username' => 'seivrtd',
    'goals' => 63,
    'gamesPlayed' => 132,
    'wins' => 56,
    'draws' => 44,
    'losses' => 32,
    'rating' => 93.6,
    'photo' => 'seivrtd.png',
  ),
  4 => 
  array (
    'name' => 'Иван Трифонов',
    'username' => 'deltaivan',
    'goals' => 12,
    'gamesPlayed' => 190,
    'wins' => 64,
    'draws' => 57,
    'losses' => 69,
    'rating' => 83.3,
    'photo' => 'deltaivan.png',
  ),
  5 => 
  array (
    'name' => 'Nikita',
    'username' => 'iamnotnikita',
    'goals' => 61,
    'gamesPlayed' => 141,
    'wins' => 50,
    'draws' => 42,
    'losses' => 49,
    'rating' => 83.3,
    'photo' => 'iamnotnikita.png',
  ),
  6 => 
  array (
    'name' => 'Константин Кирсанов',
    'username' => 'toshnotik666',
    'goals' => 9,
    'gamesPlayed' => 107,
    'wins' => 45,
    'draws' => 32,
    'losses' => 30,
    'rating' => 80.8,
    'photo' => 'toshnotik666.png',
  ),
  7 => 
  array (
    'name' => 'Ilya Rostyagaylov',
    'username' => 'mr_snak4',
    'goals' => 12,
    'gamesPlayed' => 105,
    'wins' => 37,
    'draws' => 40,
    'losses' => 28,
    'rating' => 73.3,
    'photo' => 'mr_snak4.png',
  ),
  8 => 
  array (
    'name' => 'Дмитрий Шмелев',
    'username' => '@unknown',
    'goals' => 1,
    'gamesPlayed' => 151,
    'wins' => 50,
    'draws' => 48,
    'losses' => 53,
    'rating' => 73.1,
    'photo' => 'shmel.png',
  ),
  9 => 
  array (
    'name' => 'Руслан',
    'username' => 'AlyevRuslan',
    'goals' => 45,
    'gamesPlayed' => 209,
    'wins' => 59,
    'draws' => 69,
    'losses' => 81,
    'rating' => 71.7,
    'photo' => 'CyJlTaH1117.png',
  ),
  10 => 
  array (
    'name' => 'senya Avgan',
    'username' => 'SenyaAvgan',
    'goals' => 29,
    'gamesPlayed' => 78,
    'wins' => 31,
    'draws' => 30,
    'losses' => 17,
    'rating' => 69,
    'photo' => 'SenyaAvgan.png',
  ),
  11 => 
  array (
    'name' => 'Михаил',
    'username' => '@unknown',
    'goals' => 7,
    'gamesPlayed' => 98,
    'wins' => 39,
    'draws' => 31,
    'losses' => 28,
    'rating' => 69.7,
    'photo' => 'mixail.png',
  ),
  12 => 
  array (
    'name' => 'Igor',
    'username' => 'y0ung_m0on',
    'goals' => 21,
    'gamesPlayed' => 89,
    'wins' => 42,
    'draws' => 22,
    'losses' => 25,
    'rating' => 67.7,
    'photo' => 'igor_oru.png',
  ),
  13 => 
  array (
    'name' => 'Артем',
    'username' => '@unknown',
    'goals' => 4,
    'gamesPlayed' => 94,
    'wins' => 38,
    'draws' => 31,
    'losses' => 25,
    'rating' => 66.3,
    'photo' => 'artem.png',
  ),
  14 => 
  array (
    'name' => 'Владислав Брижатый',
    'username' => 'Mirinian',
    'goals' => 30,
    'gamesPlayed' => 173,
    'wins' => 50,
    'draws' => 54,
    'losses' => 69,
    'rating' => 60.5,
    'photo' => 'mirinian.png',
  ),
  15 => 
  array (
    'name' => 'Artem',
    'username' => 'al11114',
    'goals' => 16,
    'gamesPlayed' => 95,
    'wins' => 33,
    'draws' => 28,
    'losses' => 34,
    'rating' => 60.5,
    'photo' => 'al11114.png',
  ),
  16 => 
  array (
    'name' => 'Artem Trafimov',
    'username' => 'ArtemTrafimov',
    'goals' => 16,
    'gamesPlayed' => 116,
    'wins' => 34,
    'draws' => 46,
    'losses' => 36,
    'rating' => 59.3,
    'photo' => 'ArtemTrafimov.png',
  ),
  17 => 
  array (
    'name' => 'Святослав Спирин',
    'username' => 'svyatoslavspirin',
    'goals' => 22,
    'gamesPlayed' => 74,
    'wins' => 34,
    'draws' => 19,
    'losses' => 21,
    'rating' => 57.7,
    'photo' => 'svyatoslavspirin.png',
  ),
  18 => 
  array (
    'name' => 'Alex',
    'username' => 'Sashok1122',
    'goals' => 23,
    'gamesPlayed' => 93,
    'wins' => 30,
    'draws' => 29,
    'losses' => 34,
    'rating' => 56.3,
    'photo' => 'sashok.png',
  ),
  19 => 
  array (
    'name' => 'Филипп',
    'username' => 'filipps1',
    'goals' => 13,
    'gamesPlayed' => 91,
    'wins' => 30,
    'draws' => 37,
    'losses' => 24,
    'rating' => 56.8,
    'photo' => 'filipps1.png',
  ),
  20 => 
  array (
    'name' => 'Влад',
    'username' => 'vl_l24',
    'goals' => 16,
    'gamesPlayed' => 99,
    'wins' => 29,
    'draws' => 39,
    'losses' => 31,
    'rating' => 56.9,
    'photo' => 'vl_l24.png',
  ),
  21 => 
  array (
    'name' => 'Vyacheslav Batrakov',
    'username' => '@unknown',
    'goals' => 27,
    'gamesPlayed' => 161,
    'wins' => 49,
    'draws' => 49,
    'losses' => 63,
    'rating' => 54.1,
    'photo' => 'vacheslav.png',
  ),
  22 => 
  array (
    'name' => 'Александр Акулов',
    'username' => '@unknown',
    'goals' => 8,
    'gamesPlayed' => 86,
    'wins' => 28,
    'draws' => 34,
    'losses' => 24,
    'rating' => 51.9,
    'photo' => 'akylov.png',
  ),
  23 => 
  array (
    'name' => 'Изат',
    'username' => 'izi0895',
    'goals' => 6,
    'gamesPlayed' => 76,
    'wins' => 24,
    'draws' => 32,
    'losses' => 20,
    'rating' => 48.9,
    'photo' => 'izi0895.png',
  ),
  24 => 
  array (
    'name' => 'Евгений',
    'username' => 'ZhekaFootball',
    'goals' => 30,
    'gamesPlayed' => 118,
    'wins' => 41,
    'draws' => 29,
    'losses' => 48,
    'rating' => 49.6,
    'photo' => 'Evgenkozl.png',
  ),
  25 => 
  array (
    'name' => 'Кирилл Романов',
    'username' => '@unknown',
    'goals' => 7,
    'gamesPlayed' => 66,
    'wins' => 21,
    'draws' => 29,
    'losses' => 16,
    'rating' => 49.2,
    'photo' => 'romanov.png',
  ),
  26 => 
  array (
    'name' => 'Илья Гаврилов',
    'username' => 'Gavrilovram',
    'goals' => 22,
    'gamesPlayed' => 21,
    'wins' => 17,
    'draws' => 3,
    'losses' => 1,
    'rating' => 47.4,
    'photo' => 'Gavrilov.png',
  ),
  27 => 
  array (
    'name' => 'delay_kpacubo',
    'username' => 'delay_kpacubo',
    'goals' => 13,
    'gamesPlayed' => 27,
    'wins' => 20,
    'draws' => 4,
    'losses' => 3,
    'rating' => 47.6,
    'photo' => 'kpacubo.png',
  ),
  28 => 
  array (
    'name' => 'Vadim',
    'username' => 'Vadimka_brrrr',
    'goals' => 15,
    'gamesPlayed' => 65,
    'wins' => 25,
    'draws' => 22,
    'losses' => 18,
    'rating' => 42.7,
    'photo' => 'Vadimka_brrrr.png',
  ),
  29 => 
  array (
    'name' => 'Михаил Кошелев',
    'username' => '@unknown',
    'goals' => 7,
    'gamesPlayed' => 58,
    'wins' => 19,
    'draws' => 19,
    'losses' => 20,
    'rating' => 41.6,
    'photo' => 'Mikhail.png',
  ),
  30 => 
  array (
    'name' => 'Александр',
    'username' => '@unknown',
    'goals' => 36,
    'gamesPlayed' => 58,
    'wins' => 24,
    'draws' => 11,
    'losses' => 23,
    'rating' => 42.2,
    'photo' => 'aleksandr.png',
  ),
  31 => 
  array (
    'name' => 'Евгений Швецов',
    'username' => 'evgeniyshvetsov',
    'goals' => 17,
    'gamesPlayed' => 78,
    'wins' => 24,
    'draws' => 20,
    'losses' => 34,
    'rating' => 40,
    'photo' => 'evgeniyshvetsov.png',
  ),
  32 => 
  array (
    'name' => 'Тима',
    'username' => 't1ma27',
    'goals' => 13,
    'gamesPlayed' => 130,
    'wins' => 40,
    'draws' => 35,
    'losses' => 55,
    'rating' => 40.7,
    'photo' => 't1ma27.png',
  ),
  33 => 
  array (
    'name' => 'Jorik',
    'username' => '@unknown',
    'goals' => 5,
    'gamesPlayed' => 67,
    'wins' => 22,
    'draws' => 16,
    'losses' => 29,
    'rating' => 37.8,
    'photo' => 'jorik.png',
  ),
  34 => 
  array (
    'name' => 'Александер',
    'username' => 'alexdugar59',
    'goals' => 12,
    'gamesPlayed' => 24,
    'wins' => 14,
    'draws' => 4,
    'losses' => 6,
    'rating' => 38.5,
    'photo' => 'alexdugar59.png',
  ),
  35 => 
  array (
    'name' => 'Дима',
    'username' => 'dergaev94',
    'goals' => 6,
    'gamesPlayed' => 22,
    'wins' => 15,
    'draws' => 4,
    'losses' => 3,
    'rating' => 36.7,
    'photo' => 'dergaev.png',
  ),
  36 => 
  array (
    'name' => 'Ravil\' Ravil\'',
    'username' => '@unknown',
    'goals' => 7,
    'gamesPlayed' => 65,
    'wins' => 25,
    'draws' => 17,
    'losses' => 23,
    'rating' => 35.1,
    'photo' => 'Ravil.png',
  ),
  37 => 
  array (
    'name' => 'Антон Неуймин',
    'username' => 'KroxaAn',
    'goals' => 13,
    'gamesPlayed' => 114,
    'wins' => 37,
    'draws' => 24,
    'losses' => 53,
    'rating' => 35.6,
    'photo' => 'KroxaAn.png',
  ),
  38 => 
  array (
    'name' => 'Nikita Alexandrovich',
    'username' => 'nikita_a1exandrovich',
    'goals' => 28,
    'gamesPlayed' => 90,
    'wins' => 27,
    'draws' => 21,
    'losses' => 42,
    'rating' => 34,
    'photo' => 'nikita.png',
  ),
  39 => 
  array (
    'name' => 'Sergey',
    'username' => 'KhroSe',
    'goals' => 3,
    'gamesPlayed' => 80,
    'wins' => 28,
    'draws' => 25,
    'losses' => 27,
    'rating' => 33.9,
    'photo' => 'KhroSe.png',
  ),
  40 => 
  array (
    'name' => 'Абдулатип',
    'username' => 'Abdulatip44',
    'goals' => 12,
    'gamesPlayed' => 78,
    'wins' => 26,
    'draws' => 24,
    'losses' => 28,
    'rating' => 32.5,
    'photo' => 'Abdulatip44.png',
  ),
  41 => 
  array (
    'name' => 'Evgenii',
    'username' => 'vpapalame',
    'goals' => 5,
    'gamesPlayed' => 48,
    'wins' => 13,
    'draws' => 18,
    'losses' => 17,
    'rating' => 30,
    'photo' => 'vpapalame.png',
  ),
  42 => 
  array (
    'name' => 'Ivan Ipets',
    'username' => 'IIpets',
    'goals' => 12,
    'gamesPlayed' => 39,
    'wins' => 17,
    'draws' => 10,
    'losses' => 12,
    'rating' => 30.1,
    'photo' => 'IIpets.png',
  ),
  43 => 
  array (
    'name' => 'Алексей Прокопчук',
    'username' => 'Alexey_1803',
    'goals' => 1,
    'gamesPlayed' => 20,
    'wins' => 9,
    'draws' => 8,
    'losses' => 3,
    'rating' => 27,
    'photo' => 'Alexey_1803.png',
  ),
  44 => 
  array (
    'name' => 'Владислав',
    'username' => 'Perunov_Vladislav',
    'goals' => 3,
    'gamesPlayed' => 24,
    'wins' => 13,
    'draws' => 6,
    'losses' => 5,
    'rating' => 27.9,
    'photo' => 'Perunov_Vladislav.png',
  ),
  45 => 
  array (
    'name' => 'Сергей',
    'username' => '@unknown',
    'goals' => 11,
    'gamesPlayed' => 38,
    'wins' => 16,
    'draws' => 9,
    'losses' => 13,
    'rating' => 28.7,
    'photo' => 'sergey.png',
  ),
  46 => 
  array (
    'name' => 'Алексей.',
    'username' => 'AlexeiD2025',
    'goals' => 2,
    'gamesPlayed' => 25,
    'wins' => 12,
    'draws' => 11,
    'losses' => 2,
    'rating' => 27.8,
    'photo' => 'AlexeiD2025.png',
  ),
  47 => 
  array (
    'name' => 'Андреев Алексей',
    'username' => 'Aleksey_AS_NR',
    'goals' => 8,
    'gamesPlayed' => 48,
    'wins' => 15,
    'draws' => 13,
    'losses' => 20,
    'rating' => 25.6,
    'photo' => 'Aleksey_AS_NR.png',
  ),
  48 => 
  array (
    'name' => 'Egor',
    'username' => 'legor62',
    'goals' => 7,
    'gamesPlayed' => 39,
    'wins' => 15,
    'draws' => 13,
    'losses' => 11,
    'rating' => 26,
    'photo' => 'legor62.png',
  ),
  49 => 
  array (
    'name' => 'Konstantin Chekanov',
    'username' => 'KonstantinChekanov',
    'goals' => 10,
    'gamesPlayed' => 57,
    'wins' => 14,
    'draws' => 20,
    'losses' => 22,
    'rating' => 23,
    'photo' => 'KonstantinChekanov.png',
  ),
  50 => 
  array (
    'name' => 'Artemii Tikhonov',
    'username' => 'ArtemiiTikhonov',
    'goals' => 0,
    'gamesPlayed' => 16,
    'wins' => 8,
    'draws' => 4,
    'losses' => 4,
    'rating' => 22,
    'photo' => 'ArtemiiTikhonov.png',
  ),
  51 => 
  array (
    'name' => 'Павел Ряховский',
    'username' => 'ryakhovskyp',
    'goals' => 0,
    'gamesPlayed' => 13,
    'wins' => 8,
    'draws' => 2,
    'losses' => 3,
    'rating' => 21.5,
    'photo' => 'ryakhovskyp.png',
  ),
  52 => 
  array (
    'name' => 'Александр',
    'username' => 'ridestreet',
    'goals' => 1,
    'gamesPlayed' => 31,
    'wins' => 9,
    'draws' => 10,
    'losses' => 12,
    'rating' => 19.5,
    'photo' => 'ridestreet.png',
  ),
  53 => 
  array (
    'name' => 'Niki Fedosov',
    'username' => '@unknown',
    'goals' => 4,
    'gamesPlayed' => 25,
    'wins' => 8,
    'draws' => 10,
    'losses' => 7,
    'rating' => 20.2,
    'photo' => 'niki.png',
  ),
  54 => 
  array (
    'name' => 'я глеб(',
    'username' => 'gdemoi17let',
    'goals' => 5,
    'gamesPlayed' => 19,
    'wins' => 7,
    'draws' => 5,
    'losses' => 7,
    'rating' => 18,
    'photo' => 'gdemoi17let.png',
  ),
  55 => 
  array (
    'name' => 'Кодиржон',
    'username' => '@unknown',
    'goals' => 0,
    'gamesPlayed' => 15,
    'wins' => 7,
    'draws' => 4,
    'losses' => 4,
    'rating' => 18.5,
    'photo' => 'kodirjon.png',
  ),
  56 => 
  array (
    'name' => 'Andrey',
    'username' => 'AndrewDfyf2',
    'goals' => 0,
    'gamesPlayed' => 31,
    'wins' => 9,
    'draws' => 13,
    'losses' => 9,
    'rating' => 17.9,
    'photo' => 'AndrewDfyf2.png',
  ),
  57 => 
  array (
    'name' => 'ArsenAr89',
    'username' => 'ArsenAr89',
    'goals' => 2,
    'gamesPlayed' => 14,
    'wins' => 6,
    'draws' => 7,
    'losses' => 1,
    'rating' => 18.1,
    'photo' => 'ArsenAr89.png',
  ),
  58 => 
  array (
    'name' => 'Pavel Chizhov',
    'username' => 'PChizhov87',
    'goals' => 5,
    'gamesPlayed' => 18,
    'wins' => 9,
    'draws' => 3,
    'losses' => 6,
    'rating' => 16.8,
    'photo' => 'PChizhov87.png',
  ),
  59 => 
  array (
    'name' => 'SMOOGA',
    'username' => 'SMGGETT',
    'goals' => 7,
    'gamesPlayed' => 35,
    'wins' => 9,
    'draws' => 14,
    'losses' => 12,
    'rating' => 17.3,
    'photo' => 'SMGGETT.png',
  ),
  60 => 
  array (
    'name' => 'Pavel Lonshchakov',
    'username' => '@unknown',
    'goals' => 10,
    'gamesPlayed' => 35,
    'wins' => 11,
    'draws' => 9,
    'losses' => 15,
    'rating' => 16.6,
    'photo' => 'Lonshchakov.png',
  ),
  61 => 
  array (
    'name' => 'Виктор Верходанов',
    'username' => 'Verhobanov1983',
    'goals' => 3,
    'gamesPlayed' => 20,
    'wins' => 9,
    'draws' => 6,
    'losses' => 5,
    'rating' => 16.3,
    'photo' => 'Verhobanov1983.png',
  ),
  62 => 
  array (
    'name' => 'Сергей Горшков',
    'username' => 'gos_it_tech',
    'goals' => 14,
    'gamesPlayed' => 19,
    'wins' => 8,
    'draws' => 3,
    'losses' => 8,
    'rating' => 15.9,
    'photo' => 'gos_it_tech.png',
  ),
  63 => 
  array (
    'name' => 'Igor Tatarinov',
    'username' => '@unknown',
    'goals' => 3,
    'gamesPlayed' => 18,
    'wins' => 6,
    'draws' => 5,
    'losses' => 7,
    'rating' => 14.5,
    'photo' => 'Tatarinov.png',
  ),
  64 => 
  array (
    'name' => 'Alexsandr',
    'username' => 'Cosmoc52',
    'goals' => 2,
    'gamesPlayed' => 34,
    'wins' => 12,
    'draws' => 10,
    'losses' => 12,
    'rating' => 14.8,
    'photo' => 'Cosmoc52.png',
  ),
  65 => 
  array (
    'name' => 'Вадик',
    'username' => 'Vadik_69_11',
    'goals' => 7,
    'gamesPlayed' => 15,
    'wins' => 6,
    'draws' => 3,
    'losses' => 6,
    'rating' => 13.8,
    'photo' => 'Vadik.png',
  ),
  66 => 
  array (
    'name' => 'JustahumanMy',
    'username' => 'JustahumanMy',
    'goals' => 0,
    'gamesPlayed' => 30,
    'wins' => 6,
    'draws' => 11,
    'losses' => 13,
    'rating' => 13.5,
    'photo' => 'JustahumanMy.png',
  ),
  67 => 
  array (
    'name' => 'NizHgaN',
    'username' => 'NizHgaN',
    'goals' => 0,
    'gamesPlayed' => 6,
    'wins' => 4,
    'draws' => 2,
    'losses' => 0,
    'rating' => 14,
    'photo' => 'NizHgaN.png',
  ),
  68 => 
  array (
    'name' => 'GDI',
    'username' => '@unknown',
    'goals' => 1,
    'gamesPlayed' => 7,
    'wins' => 4,
    'draws' => 2,
    'losses' => 1,
    'rating' => 13,
    'photo' => 'gdi.png',
  ),
  69 => 
  array (
    'name' => 'Sergey Deshevoy',
    'username' => 'Pedro_Barb0sa',
    'goals' => 6,
    'gamesPlayed' => 34,
    'wins' => 10,
    'draws' => 11,
    'losses' => 13,
    'rating' => 13.2,
    'photo' => 'Pedro_Barb0sa.png',
  ),
  70 => 
  array (
    'name' => 'Владимир',
    'username' => 'BarDblga',
    'goals' => 4,
    'gamesPlayed' => 19,
    'wins' => 5,
    'draws' => 6,
    'losses' => 8,
    'rating' => 11,
    'photo' => 'BarDblga.png',
  ),
  71 => 
  array (
    'name' => 'Vlades 19',
    'username' => '@unknown',
    'goals' => 2,
    'gamesPlayed' => 12,
    'wins' => 6,
    'draws' => 2,
    'losses' => 4,
    'rating' => 11.4,
    'photo' => 'Vlades.png',
  ),
  72 => 
  array (
    'name' => 'Сергей Матвеев',
    'username' => '@unknown',
    'goals' => 2,
    'gamesPlayed' => 16,
    'wins' => 4,
    'draws' => 9,
    'losses' => 3,
    'rating' => 11.1,
    'photo' => 'matveev.png',
  ),
  73 => 
  array (
    'name' => 'Александр Силкин',
    'username' => 'silkin_xandr',
    'goals' => 8,
    'gamesPlayed' => 25,
    'wins' => 4,
    'draws' => 14,
    'losses' => 7,
    'rating' => 11.9,
    'photo' => 'silkin_handr.png',
  ),
  74 => 
  array (
    'name' => 'And Saf',
    'username' => '@unknown',
    'goals' => 2,
    'gamesPlayed' => 23,
    'wins' => 7,
    'draws' => 10,
    'losses' => 6,
    'rating' => 12.2,
    'photo' => 'AndSaf.png',
  ),
  75 => 
  array (
    'name' => 'Владимир Козлов',
    'username' => 'kozzzlov',
    'goals' => 0,
    'gamesPlayed' => 30,
    'wins' => 8,
    'draws' => 11,
    'losses' => 11,
    'rating' => 12,
    'photo' => 'kozzzlov.png',
  ),
  76 => 
  array (
    'name' => 'Антон Данилов',
    'username' => 'toxa1392777',
    'goals' => 4,
    'gamesPlayed' => 15,
    'wins' => 6,
    'draws' => 3,
    'losses' => 6,
    'rating' => 12.3,
    'photo' => 'toxa1392777.png',
  ),
  77 => 
  array (
    'name' => 'Алексей',
    'username' => 'alexey19m',
    'goals' => 0,
    'gamesPlayed' => 6,
    'wins' => 4,
    'draws' => 1,
    'losses' => 1,
    'rating' => 11.5,
    'photo' => 'alexe19m.png',
  ),
  78 => 
  array (
    'name' => 'Сергей Lazio',
    'username' => '@unknown',
    'goals' => 0,
    'gamesPlayed' => 6,
    'wins' => 4,
    'draws' => 1,
    'losses' => 1,
    'rating' => 11.5,
    'photo' => 'Lazio.png',
  ),
  79 => 
  array (
    'name' => 'D',
    'username' => 'DMITRIY_MSK_V',
    'goals' => 0,
    'gamesPlayed' => 8,
    'wins' => 2,
    'draws' => 5,
    'losses' => 1,
    'rating' => 9.5,
    'photo' => 'DMITRIY_MSK_V.png',
  ),
  80 => 
  array (
    'name' => 'Иван',
    'username' => '@unknown',
    'goals' => 0,
    'gamesPlayed' => 5,
    'wins' => 5,
    'draws' => 0,
    'losses' => 0,
    'rating' => 10,
    'photo' => 'ivan.png',
  ),
  81 => 
  array (
    'name' => 'Diego Armando',
    'username' => 'frankie_dux',
    'goals' => 0,
    'gamesPlayed' => 8,
    'wins' => 4,
    'draws' => 4,
    'losses' => 0,
    'rating' => 10,
    'photo' => 'frankie_dux.png',
  ),
  82 => 
  array (
    'name' => 'KV-19',
    'username' => '@unknown',
    'goals' => 5,
    'gamesPlayed' => 28,
    'wins' => 9,
    'draws' => 6,
    'losses' => 13,
    'rating' => 10.5,
    'photo' => 'KV-19.png',
  ),
  83 => 
  array (
    'name' => 'Дмитрий З',
    'username' => '@unknown',
    'goals' => 3,
    'gamesPlayed' => 37,
    'wins' => 9,
    'draws' => 11,
    'losses' => 17,
    'rating' => 9.9,
    'photo' => 'dmitri.png',
  ),
  84 => 
  array (
    'name' => 'Petr Pushkarev',
    'username' => 'iLikeTP',
    'goals' => 1,
    'gamesPlayed' => 32,
    'wins' => 7,
    'draws' => 6,
    'losses' => 19,
    'rating' => 7.7,
    'photo' => 'iLikeTP.png',
  ),
  85 => 
  array (
    'name' => 'Artem Rodin',
    'username' => 'RodnoyAR',
    'goals' => 7,
    'gamesPlayed' => 22,
    'wins' => 6,
    'draws' => 6,
    'losses' => 10,
    'rating' => 7.7,
    'photo' => 'RodnoyAR.png',
  ),
  86 => 
  array (
    'name' => 'Ryzholda13',
    'username' => 'rysholda13',
    'goals' => 0,
    'gamesPlayed' => 6,
    'wins' => 4,
    'draws' => 1,
    'losses' => 1,
    'rating' => 8.5,
    'photo' => 'rysholda13.png',
  ),
  87 => 
  array (
    'name' => 'Даниил Ильин',
    'username' => 'desantiiago',
    'goals' => 1,
    'gamesPlayed' => 10,
    'wins' => 4,
    'draws' => 4,
    'losses' => 2,
    'rating' => 8.3,
    'photo' => 'desantiiago.png',
  ),
  88 => 
  array (
    'name' => 'Rioting',
    'username' => 'vehrbrvk50',
    'goals' => 5,
    'gamesPlayed' => 5,
    'wins' => 3,
    'draws' => 0,
    'losses' => 2,
    'rating' => 7.5,
    'photo' => 'vehrbrvk50.png',
  ),
  89 => 
  array (
    'name' => 'Константин Орлов',
    'username' => 'freza01',
    'goals' => 1,
    'gamesPlayed' => 6,
    'wins' => 2,
    'draws' => 4,
    'losses' => 0,
    'rating' => 6.5,
    'photo' => 'freza01.png',
  ),
  90 => 
  array (
    'name' => 'Anton Zakharov',
    'username' => 'fucking1986',
    'goals' => 0,
    'gamesPlayed' => 12,
    'wins' => 5,
    'draws' => 1,
    'losses' => 6,
    'rating' => 6,
    'photo' => 'fucking1986.png',
  ),
  91 => 
  array (
    'name' => '.',
    'username' => 'game_on_manneger',
    'goals' => 0,
    'gamesPlayed' => 21,
    'wins' => 5,
    'draws' => 10,
    'losses' => 6,
    'rating' => 6,
    'photo' => 'game_on_manneger.png',
  ),
  92 => 
  array (
    'name' => 'Алекс Алекс',
    'username' => '@unknown',
    'goals' => 3,
    'gamesPlayed' => 27,
    'wins' => 5,
    'draws' => 10,
    'losses' => 12,
    'rating' => 6.5,
    'photo' => 'aleks.png',
  ),
  93 => 
  array (
    'name' => 'Анатолий',
    'username' => '@unknown',
    'goals' => 1,
    'gamesPlayed' => 7,
    'wins' => 3,
    'draws' => 1,
    'losses' => 3,
    'rating' => 6,
    'photo' => 'anatoli.png',
  ),
  94 => 
  array (
    'name' => 'Андрей',
    'username' => 'Lu4nikk',
    'goals' => 0,
    'gamesPlayed' => 18,
    'wins' => 6,
    'draws' => 3,
    'losses' => 9,
    'rating' => 5,
    'photo' => 'andr.png',
  ),
  95 => 
  array (
    'name' => 'ru$$ikk',
    'username' => 'Ruslan444ikk',
    'goals' => 1,
    'gamesPlayed' => 7,
    'wins' => 3,
    'draws' => 2,
    'losses' => 2,
    'rating' => 5.5,
    'photo' => 'Ruslan444ikk.png',
  ),
  96 => 
  array (
    'name' => 'Kirill K',
    'username' => 'Xpycts',
    'goals' => 0,
    'gamesPlayed' => 6,
    'wins' => 2,
    'draws' => 4,
    'losses' => 0,
    'rating' => 6,
    'photo' => 'Xpycts.png',
  ),
  97 => 
  array (
    'name' => 'دانيلكا',
    'username' => 'R_kirpichik',
    'goals' => 3,
    'gamesPlayed' => 8,
    'wins' => 3,
    'draws' => 2,
    'losses' => 3,
    'rating' => 6,
    'photo' => 'R_kirpichik.png',
  ),
  98 => 
  array (
    'name' => 'Александр Коротков',
    'username' => 'Crespo199319993',
    'goals' => 0,
    'gamesPlayed' => 7,
    'wins' => 3,
    'draws' => 3,
    'losses' => 1,
    'rating' => 6.5,
    'photo' => 'Crespo199319993.png',
  ),
  99 => 
  array (
    'name' => 'Тим',
    'username' => 'TimRamen',
    'goals' => 2,
    'gamesPlayed' => 14,
    'wins' => 5,
    'draws' => 2,
    'losses' => 7,
    'rating' => 3.6,
    'photo' => 'TimRamen.png',
  ),
  100 => 
  array (
    'name' => 'ᑎᗣᗯᏦᗣ',
    'username' => 'HA_3AKATE_KAPbEPbI',
    'goals' => 12,
    'gamesPlayed' => 6,
    'wins' => 1,
    'draws' => 1,
    'losses' => 4,
    'rating' => 4,
    'photo' => 'zakat.png',
  ),
  101 => 
  array (
    'name' => 'Сергей Прокопцов',
    'username' => 'Sirgey_zizy',
    'goals' => 0,
    'gamesPlayed' => 8,
    'wins' => 1,
    'draws' => 6,
    'losses' => 1,
    'rating' => 4.5,
    'photo' => 'Sirgey_zizy.png',
  ),
  102 => 
  array (
    'name' => 'Игош',
    'username' => '@unknown',
    'goals' => 1,
    'gamesPlayed' => 28,
    'wins' => 7,
    'draws' => 5,
    'losses' => 16,
    'rating' => 3.5,
    'photo' => 'igosh.png',
  ),
  103 => 
  array (
    'name' => 'Max Rakhmankin',
    'username' => 'umeprel',
    'goals' => 0,
    'gamesPlayed' => 19,
    'wins' => 5,
    'draws' => 5,
    'losses' => 9,
    'rating' => 4,
    'photo' => 'umeprel.png',
  ),
  104 => 
  array (
    'name' => 'Николай Сапотницкий',
    'username' => 'Spasatel_1731',
    'goals' => 1,
    'gamesPlayed' => 6,
    'wins' => 3,
    'draws' => 0,
    'losses' => 3,
    'rating' => 3.3,
    'photo' => 'Spasatel_1731.png',
  ),
  105 => 
  array (
    'name' => 'Stanislav Solomin',
    'username' => '@unknown',
    'goals' => 0,
    'gamesPlayed' => 6,
    'wins' => 1,
    'draws' => 3,
    'losses' => 2,
    'rating' => 3,
    'photo' => 'Solomin.png',
  ),
  106 => 
  array (
    'name' => 'Aleksandr Galanov',
    'username' => 'galanovfitness',
    'goals' => 2,
    'gamesPlayed' => 6,
    'wins' => 2,
    'draws' => 1,
    'losses' => 3,
    'rating' => 3.5,
    'photo' => 'galanovfitness.png',
  ),
  107 => 
  array (
    'name' => 'Дмитрий',
    'username' => 'taltskov',
    'goals' => 1,
    'gamesPlayed' => 6,
    'wins' => 2,
    'draws' => 1,
    'losses' => 3,
    'rating' => 3,
    'photo' => 'taltskov.png',
  ),
  108 => 
  array (
    'name' => 'Артем Перегудов',
    'username' => 'Artibai',
    'goals' => 0,
    'gamesPlayed' => 7,
    'wins' => 3,
    'draws' => 1,
    'losses' => 3,
    'rating' => 3.5,
    'photo' => 'Artibai.png',
  ),
  109 => 
  array (
    'name' => 'Тримонов Николай',
    'username' => 'N_Trimonov',
    'goals' => 3,
    'gamesPlayed' => 13,
    'wins' => 3,
    'draws' => 3,
    'losses' => 7,
    'rating' => 3.5,
    'photo' => 'N_Trimonov.png',
  ),
  110 => 
  array (
    'name' => 'Андрей Корунов',
    'username' => 'ankorn1694',
    'goals' => 2,
    'gamesPlayed' => 6,
    'wins' => 1,
    'draws' => 2,
    'losses' => 3,
    'rating' => 1.5,
    'photo' => 'ankorn1694.png',
  ),
  111 => 
  array (
    'name' => 'German Zavgar',
    'username' => 'germanitto',
    'goals' => 0,
    'gamesPlayed' => 16,
    'wins' => 1,
    'draws' => 9,
    'losses' => 6,
    'rating' => 1.5,
    'photo' => 'germanitto.png',
  ),
  112 => 
  array (
    'name' => 'Viktor DoBronx',
    'username' => 'Iatinose',
    'goals' => 0,
    'gamesPlayed' => 14,
    'wins' => 3,
    'draws' => 3,
    'losses' => 8,
    'rating' => 2,
    'photo' => 'Iatinose.png',
  ),
  113 => 
  array (
    'name' => 'Максим М',
    'username' => 'mbodunov078',
    'goals' => 1,
    'gamesPlayed' => 1,
    'wins' => 1,
    'draws' => 0,
    'losses' => 0,
    'rating' => 2.3,
    'photo' => 'mbodunov.png',
  ),
  114 => 
  array (
    'name' => 'Евгений',
    'username' => 'Jony8603',
    'goals' => 0,
    'gamesPlayed' => 8,
    'wins' => 2,
    'draws' => 2,
    'losses' => 4,
    'rating' => 2,
    'photo' => 'Jony8603.png',
  ),
  115 => 
  array (
    'name' => 'Lexus85 .!.',
    'username' => '@unknown',
    'goals' => 0,
    'gamesPlayed' => 5,
    'wins' => 1,
    'draws' => 2,
    'losses' => 2,
    'rating' => 1,
    'photo' => 'default.jpg',
  ),
  116 => 
  array (
    'name' => 'HUNTER',
    'username' => 'HUNTER100983',
    'goals' => 1,
    'gamesPlayed' => 16,
    'wins' => 4,
    'draws' => 4,
    'losses' => 8,
    'rating' => 1.8,
    'photo' => 'HUNTER100983.png',
  ),
  117 => 
  array (
    'name' => 'Игорь Ковязин',
    'username' => 'mi28nm',
    'goals' => 1,
    'gamesPlayed' => 12,
    'wins' => 2,
    'draws' => 4,
    'losses' => 6,
    'rating' => 1.5,
    'photo' => 'mi28nm.png',
  ),
  118 => 
  array (
    'name' => 'Данил',
    'username' => '@unknown',
    'goals' => 2,
    'gamesPlayed' => 7,
    'wins' => 0,
    'draws' => 1,
    'losses' => 6,
    'rating' => 0,
    'photo' => 'danil.png',
  ),
  119 => 
  array (
    'name' => 'Seana',
    'username' => 'faserq',
    'goals' => 1,
    'gamesPlayed' => 12,
    'wins' => 0,
    'draws' => 2,
    'losses' => 10,
    'rating' => 0,
    'photo' => 'faserq.png',
  ),
  120 => 
  array (
    'name' => 'Alexey Neponyatno',
    'username' => 'alexey_neponyatno',
    'goals' => 1,
    'gamesPlayed' => 5,
    'wins' => 1,
    'draws' => 0,
    'losses' => 4,
    'rating' => 0,
    'photo' => 'default.jpg',
  ),
  121 => 
  array (
    'name' => 'Vyn Lavanda',
    'username' => 'VynLavanda',
    'goals' => 0,
    'gamesPlayed' => 15,
    'wins' => 0,
    'draws' => 3,
    'losses' => 12,
    'rating' => 0,
    'photo' => 'VynLavanda.png',
  ),
  122 => 
  array (
    'name' => 'Павел Штепа',
    'username' => 'Paxan4',
    'goals' => 0,
    'gamesPlayed' => 1,
    'wins' => 0,
    'draws' => 0,
    'losses' => 1,
    'rating' => 0,
    'photo' => 'Paxan4.png',
  ),
  123 => 
  array (
    'name' => 'Даниил',
    'username' => 'danchik284',
    'goals' => 0,
    'gamesPlayed' => 18,
    'wins' => 2,
    'draws' => 6,
    'losses' => 10,
    'rating' => 0,
    'photo' => 'danchik284.png',
  ),
  124 => 
  array (
    'name' => 'Never Broke Again',
    'username' => '@unknown',
    'goals' => 2,
    'gamesPlayed' => 12,
    'wins' => 2,
    'draws' => 2,
    'losses' => 8,
    'rating' => 0,
    'photo' => 'Never.png',
  ),
  125 => 
  array (
    'name' => 'Виктор Безруков',
    'username' => 'BezrukovViktor',
    'goals' => 0,
    'gamesPlayed' => 6,
    'wins' => 1,
    'draws' => 2,
    'losses' => 3,
    'rating' => 0,
    'photo' => 'BezrukovViktor.png',
  ),
  126 => 
  array (
    'name' => 'Роман Ыы',
    'username' => '@unknown',
    'goals' => 0,
    'gamesPlayed' => 8,
    'wins' => 0,
    'draws' => 5,
    'losses' => 3,
    'rating' => 0,
    'photo' => 'roman.png',
  ),
  127 => 
  array (
    'name' => 'Nikcha',
    'username' => 'Nikcha228',
    'goals' => 0,
    'gamesPlayed' => 15,
    'wins' => 0,
    'draws' => 3,
    'losses' => 12,
    'rating' => 0,
    'photo' => 'Nikcha228.png',
  ),
  128 => 
  array (
    'name' => 'В Е',
    'username' => 'valenokkk09',
    'goals' => 0,
    'gamesPlayed' => 12,
    'wins' => 2,
    'draws' => 4,
    'losses' => 6,
    'rating' => 0,
    'photo' => 'valenokkk09.png',
  ),
  129 => 
  array (
    'name' => 'Georgiy',
    'username' => 'GoshaSc',
    'goals' => 0,
    'gamesPlayed' => 13,
    'wins' => 2,
    'draws' => 3,
    'losses' => 8,
    'rating' => 0,
    'photo' => 'GoshaSc.png',
  ),
  130 => 
  array (
    'name' => 'Youdjen',
    'username' => 'gerop_il',
    'goals' => 0,
    'gamesPlayed' => 6,
    'wins' => 1,
    'draws' => 2,
    'losses' => 3,
    'rating' => 0.5,
    'photo' => 'gerop_il.png',
  ),
  131 => 
  array (
    'name' => 'Сергей',
    'username' => 'MS_Leon17',
    'goals' => 0,
    'gamesPlayed' => 6,
    'wins' => 1,
    'draws' => 1,
    'losses' => 4,
    'rating' => 0,
    'photo' => 'MS_Leon17.png',
  ),
  132 => 
  array (
    'name' => 'Денис',
    'username' => '@unknown',
    'goals' => 2,
    'gamesPlayed' => 28,
    'wins' => 6,
    'draws' => 6,
    'losses' => 16,
    'rating' => 0,
    'photo' => 'denis.png',
  ),
);
